import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import {
  Stethoscope, Brain, Calendar, Users, CreditCard, BarChart3,
  QrCode, ArrowRight, CheckCircle, Star, ChevronRight, Shield,
  Zap, Globe, HeartPulse, Activity, Clock, TrendingUp,
} from 'lucide-react'

const features = [
  { icon: Brain, title: 'AI Medical Intelligence', desc: 'Smart diagnosis assistance, automated summaries, and predictive patient analytics powered by Gemini AI.', color: 'from-violet-500 to-purple-600' },
  { icon: Calendar, title: 'Smart Appointments', desc: 'Intelligent scheduling with auto-reminders, queue management, and emergency priority routing.', color: 'from-blue-500 to-cyan-500' },
  { icon: Users, title: 'Patient Management', desc: 'Comprehensive patient profiles, medical history, prescriptions, and real-time status tracking.', color: 'from-emerald-500 to-teal-600' },
  { icon: CreditCard, title: 'Billing & Invoicing', desc: 'Automated invoice generation, payment tracking, and downloadable receipts for seamless billing.', color: 'from-orange-500 to-amber-600' },
  { icon: BarChart3, title: 'Analytics Dashboard', desc: 'Real-time insights on revenue, patient load, doctor performance, and operational KPIs.', color: 'from-rose-500 to-pink-600' },
  { icon: QrCode, title: 'Emergency QR Wallet', desc: 'Instant patient emergency data via QR code — blood group, allergies, and emergency contacts.', color: 'from-red-500 to-orange-500' },
]

const stats = [
  { value: '12,000+', label: 'Patients Managed', icon: Users },
  { value: '98.4%', label: 'Appointment Accuracy', icon: CheckCircle },
  { value: '3.2x', label: 'Faster Billing', icon: Zap },
  { value: '240+', label: 'Clinics Onboarded', icon: Globe },
]

const testimonials = [
  { name: 'Dr. Ramesh Iyer', role: 'Chief Medical Officer, Apollo Clinic', text: 'MediSync AI transformed our patient workflow. Appointment chaos is a thing of the past.', rating: 5 },
  { name: 'Anjali Sharma', role: 'Administrator, LifeCare Hospital', text: 'The billing module alone saved us 4 hours daily. The dashboard is incredibly intuitive.', rating: 5 },
  { name: 'Dr. Sunita Nair', role: 'Cardiologist, Fortis', text: 'Patient summaries generated by AI are accurate and save me significant consultation time.', rating: 5 },
]

const pricing = [
  { plan: 'Clinic', price: '₹2,999', period: '/month', features: ['Up to 5 Doctors', '500 Patients', 'Appointments & Billing', 'Basic Analytics', 'Email Support'], popular: false },
  { plan: 'Hospital', price: '₹7,999', period: '/month', features: ['Up to 30 Doctors', 'Unlimited Patients', 'Full AI Features', 'Advanced Analytics', 'Emergency Wallet', 'Priority Support'], popular: true },
  { plan: 'Enterprise', price: 'Custom', period: '', features: ['Unlimited Doctors', 'Multi-branch Support', 'Custom Integrations', 'Dedicated Manager', 'SLA Guarantee', 'White Label'], popular: false },
]

const faqs = [
  { q: 'Is my patient data secure?', a: 'Yes, we use AES-256 encryption, HIPAA-compliant data handling, and role-based access control for complete data security.' },
  { q: 'Can I import existing patient records?', a: 'Yes, MediSync AI supports bulk CSV import and integrations with most existing EMR systems.' },
  { q: 'Is there a free trial?', a: 'We offer a 14-day free trial with full access to all Hospital plan features, no credit card required.' },
  { q: 'Does it work on mobile?', a: 'The platform is fully responsive and works seamlessly on tablets and mobile devices.' },
]

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white font-sans">
      {/* Navbar */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-white/90 backdrop-blur-xl border-b border-gray-100 shadow-sm">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-blue-600 to-cyan-500 flex items-center justify-center">
              <Stethoscope size={18} className="text-white" />
            </div>
            <span className="text-xl font-bold text-gray-900">MediSync <span className="text-gradient-medical">AI</span></span>
          </div>
          <div className="hidden md:flex items-center gap-8 text-sm font-medium text-gray-600">
            <a href="#features" className="hover:text-blue-600 transition-colors">Features</a>
            <a href="#pricing" className="hover:text-blue-600 transition-colors">Pricing</a>
            <a href="#faq" className="hover:text-blue-600 transition-colors">FAQ</a>
          </div>
          <div className="flex items-center gap-3">
            <Link to="/login" className="px-4 py-2 text-sm font-medium text-gray-700 hover:text-gray-900 transition-colors">Sign In</Link>
            <Link to="/login" className="btn-primary text-sm py-2.5 px-5">Get Started <ArrowRight size={15} /></Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative min-h-screen flex items-center overflow-hidden pt-20" style={{ background: 'linear-gradient(135deg, #03045E 0%, #023E8A 40%, #0077B6 70%, #00B4D8 100%)' }}>
        <div className="absolute inset-0 hero-grid" />
        <div className="hero-glow top-1/4 left-1/4 -translate-x-1/2 -translate-y-1/2" style={{ position: 'absolute' }} />
        <div className="hero-glow bottom-0 right-1/4" style={{ position: 'absolute' }} />

        <div className="relative max-w-7xl mx-auto px-6 py-24 grid lg:grid-cols-2 gap-16 items-center">
          <motion.div initial={{ opacity: 0, x: -40 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.7 }}>
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/10 border border-white/20 text-cyan-300 text-sm font-medium mb-6">
              <HeartPulse size={14} className="animate-pulse" />
              AI-Powered Healthcare Platform
            </div>
            <h1 className="text-5xl lg:text-6xl font-black text-white leading-tight mb-6">
              The Future of<br />
              <span className="gradient-text-hero">Hospital Management</span>
            </h1>
            <p className="text-lg text-blue-100 leading-relaxed mb-8 max-w-lg">
              Streamline patient care, automate workflows, and unlock AI-powered insights. One platform for hospitals, clinics, doctors, and patients.
            </p>
            <div className="flex flex-wrap gap-4 mb-12">
              <Link to="/login" className="inline-flex items-center gap-2 px-7 py-4 rounded-xl font-bold text-medical-navy bg-white hover:bg-blue-50 transition-all duration-200 shadow-lg hover:-translate-y-0.5 hover:shadow-xl">
                Start Free Trial <ArrowRight size={16} />
              </Link>
              <Link to="/login" className="inline-flex items-center gap-2 px-7 py-4 rounded-xl font-bold text-white border-2 border-white/30 hover:border-white hover:bg-white/10 transition-all duration-200">
                View Demo <ChevronRight size={16} />
              </Link>
            </div>
            <div className="flex flex-wrap gap-6">
              {['HIPAA Compliant', 'Free 14-day trial', 'No credit card'].map(t => (
                <div key={t} className="flex items-center gap-2 text-sm text-blue-200">
                  <CheckCircle size={14} className="text-emerald-400" /> {t}
                </div>
              ))}
            </div>
          </motion.div>

          {/* Dashboard mockup */}
          <motion.div initial={{ opacity: 0, x: 40 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.7, delay: 0.2 }} className="hidden lg:block">
            <div className="relative">
              <div className="bg-white/10 backdrop-blur-xl border border-white/20 rounded-3xl p-6 shadow-2xl">
                <div className="flex items-center gap-2 mb-4">
                  <div className="w-3 h-3 rounded-full bg-red-400" />
                  <div className="w-3 h-3 rounded-full bg-yellow-400" />
                  <div className="w-3 h-3 rounded-full bg-emerald-400" />
                  <span className="ml-2 text-xs text-white/60">MediSync AI — Admin Dashboard</span>
                </div>
                {/* Mini dashboard preview */}
                <div className="grid grid-cols-2 gap-3 mb-4">
                  {[
                    { label: 'Total Patients', val: '1,284', color: 'from-blue-500 to-cyan-400' },
                    { label: "Today's Revenue", val: '₹2.78L', color: 'from-emerald-500 to-teal-400' },
                    { label: 'Appointments', val: '87', color: 'from-violet-500 to-purple-400' },
                    { label: 'Active Doctors', val: '48', color: 'from-rose-500 to-pink-400' },
                  ].map(card => (
                    <div key={card.label} className="bg-white/10 rounded-xl p-3">
                      <div className={`text-xs font-medium text-white/60 mb-1`}>{card.label}</div>
                      <div className={`text-xl font-black bg-gradient-to-r ${card.color} bg-clip-text text-transparent`}>{card.val}</div>
                    </div>
                  ))}
                </div>
                {/* Fake chart bars */}
                <div className="bg-white/10 rounded-xl p-3 mb-3">
                  <div className="text-xs text-white/60 mb-2">Weekly Revenue</div>
                  <div className="flex items-end gap-1.5 h-14">
                    {[40, 65, 55, 80, 70, 90, 78].map((h, i) => (
                      <div key={i} className="flex-1 rounded-t-md bg-gradient-to-t from-cyan-500 to-blue-400 opacity-80" style={{ height: `${h}%` }} />
                    ))}
                  </div>
                </div>
                {/* Fake patient list */}
                <div className="space-y-2">
                  {['Aarav Sharma — Cardiology', 'Diya Patel — Endocrinology', 'Rajesh Gupta — Emergency ⚠️'].map(p => (
                    <div key={p} className="flex items-center gap-2 bg-white/10 rounded-lg px-3 py-2">
                      <div className="w-6 h-6 rounded-full bg-gradient-to-br from-cyan-400 to-blue-500 text-white text-xs font-bold flex items-center justify-center flex-shrink-0">{p[0]}</div>
                      <span className="text-xs text-white/80">{p}</span>
                    </div>
                  ))}
                </div>
              </div>
              {/* Floating badges */}
              <motion.div animate={{ y: [0, -8, 0] }} transition={{ duration: 3, repeat: Infinity }} className="absolute -top-4 -right-4 bg-white rounded-2xl px-4 py-3 shadow-xl">
                <div className="flex items-center gap-2">
                  <Activity size={16} className="text-emerald-500" />
                  <div>
                    <div className="text-xs font-bold text-gray-900">98.4% Uptime</div>
                    <div className="text-[10px] text-gray-500">System Status</div>
                  </div>
                </div>
              </motion.div>
              <motion.div animate={{ y: [0, 8, 0] }} transition={{ duration: 3.5, repeat: Infinity }} className="absolute -bottom-4 -left-4 bg-white rounded-2xl px-4 py-3 shadow-xl">
                <div className="flex items-center gap-2">
                  <Brain size={16} className="text-violet-500" />
                  <div>
                    <div className="text-xs font-bold text-gray-900">AI Active</div>
                    <div className="text-[10px] text-gray-500">Gemini 2.0</div>
                  </div>
                </div>
              </motion.div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Stats */}
      <section className="py-16 bg-white border-b border-gray-100">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((s, i) => (
              <motion.div key={s.label} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }} className="text-center">
                <div className="inline-flex items-center justify-center w-12 h-12 rounded-2xl bg-blue-50 mb-3">
                  <s.icon size={22} className="text-blue-600" />
                </div>
                <div className="text-3xl font-black text-gray-900 mb-1">{s.value}</div>
                <div className="text-sm text-gray-500 font-medium">{s.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-24 bg-slate-50">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-100 text-blue-700 text-sm font-semibold mb-4">
              <Zap size={14} /> Core Features
            </div>
            <h2 className="text-4xl font-black text-gray-900 mb-4">Everything Your Clinic Needs</h2>
            <p className="text-gray-500 text-lg max-w-2xl mx-auto">One unified platform replacing 6 disconnected tools — built for modern healthcare.</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((f, i) => (
              <motion.div key={f.title} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                className="bg-white rounded-2xl p-7 shadow-card hover:shadow-card-hover transition-all duration-300 hover:-translate-y-1 border border-gray-100 group">
                <div className={`w-12 h-12 rounded-2xl bg-gradient-to-br ${f.color} flex items-center justify-center mb-5 group-hover:scale-110 transition-transform duration-300`}>
                  <f.icon size={22} className="text-white" />
                </div>
                <h3 className="font-bold text-gray-900 text-lg mb-2">{f.title}</h3>
                <p className="text-gray-500 text-sm leading-relaxed">{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Workflow */}
      <section className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-black text-gray-900 mb-4">How MediSync AI Works</h2>
            <p className="text-gray-500 text-lg">Simple 4-step workflow to digitize your entire clinic</p>
          </div>
          <div className="grid md:grid-cols-4 gap-8">
            {[
              { step: '01', title: 'Register Patients', desc: 'Quickly register patients with digital forms and instant ID generation.', icon: Users },
              { step: '02', title: 'Book Appointments', desc: 'Smart scheduling with doctor availability and priority management.', icon: Calendar },
              { step: '03', title: 'Manage Records', desc: 'AI-powered medical records, prescriptions, and history tracking.', icon: Activity },
              { step: '04', title: 'Process Billing', desc: 'Auto-generate invoices and track payments seamlessly.', icon: CreditCard },
            ].map((s, i) => (
              <motion.div key={s.step} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.15 }} className="relative text-center">
                <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-blue-600 to-cyan-500 text-white font-black text-lg mb-5 shadow-lg shadow-blue-200">
                  {s.step}
                </div>
                {i < 3 && <div className="hidden md:block absolute top-8 left-[60%] w-[80%] h-0.5 bg-gradient-to-r from-blue-200 to-cyan-200" />}
                <h3 className="font-bold text-gray-900 mb-2">{s.title}</h3>
                <p className="text-gray-500 text-sm">{s.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-24 bg-slate-50">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-black text-gray-900 mb-4">Trusted by Healthcare Professionals</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            {testimonials.map((t, i) => (
              <motion.div key={t.name} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                className="bg-white rounded-2xl p-7 shadow-card border border-gray-100">
                <div className="flex gap-1 mb-4">
                  {Array.from({ length: t.rating }).map((_, i) => <Star key={i} size={14} className="text-amber-400 fill-amber-400" />)}
                </div>
                <p className="text-gray-700 text-sm leading-relaxed mb-5 italic">"{t.text}"</p>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-500 to-cyan-400 flex items-center justify-center text-white font-bold">{t.name[0]}</div>
                  <div>
                    <div className="font-semibold text-gray-900 text-sm">{t.name}</div>
                    <div className="text-xs text-gray-500">{t.role}</div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-black text-gray-900 mb-4">Simple, Transparent Pricing</h2>
            <p className="text-gray-500 text-lg">14-day free trial on all plans. No credit card required.</p>
          </div>
          <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {pricing.map((p, i) => (
              <motion.div key={p.plan} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                className={`rounded-2xl p-8 border-2 transition-all duration-300 relative ${p.popular ? 'border-blue-500 shadow-xl shadow-blue-100 scale-105' : 'border-gray-100 shadow-card'}`}>
                {p.popular && <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-gradient-to-r from-blue-600 to-cyan-500 text-white text-xs font-bold px-4 py-1 rounded-full">Most Popular</div>}
                <div className="mb-6">
                  <h3 className="font-black text-gray-900 text-xl mb-2">{p.plan}</h3>
                  <div className="flex items-end gap-1">
                    <span className="text-4xl font-black text-gray-900">{p.price}</span>
                    <span className="text-gray-500 text-sm mb-1">{p.period}</span>
                  </div>
                </div>
                <ul className="space-y-3 mb-8">
                  {p.features.map(f => (
                    <li key={f} className="flex items-center gap-2 text-sm text-gray-600">
                      <CheckCircle size={15} className="text-emerald-500 flex-shrink-0" /> {f}
                    </li>
                  ))}
                </ul>
                <Link to="/login" className={`w-full flex items-center justify-center gap-2 py-3 rounded-xl font-bold text-sm transition-all duration-200 ${p.popular ? 'bg-gradient-to-r from-blue-600 to-cyan-500 text-white shadow-lg hover:shadow-xl hover:-translate-y-0.5' : 'border-2 border-gray-200 text-gray-700 hover:border-blue-400 hover:text-blue-600'}`}>
                  Get Started <ArrowRight size={15} />
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="py-24 bg-slate-50">
        <div className="max-w-3xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-black text-gray-900 mb-4">Frequently Asked Questions</h2>
          </div>
          <div className="space-y-4">
            {faqs.map((f, i) => (
              <motion.div key={i} initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                className="bg-white rounded-2xl p-6 shadow-card border border-gray-100">
                <h3 className="font-bold text-gray-900 mb-2 flex items-center gap-2"><Shield size={16} className="text-blue-500 flex-shrink-0" /> {f.q}</h3>
                <p className="text-gray-500 text-sm leading-relaxed">{f.a}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24" style={{ background: 'linear-gradient(135deg, #03045E 0%, #023E8A 50%, #0077B6 100%)' }}>
        <div className="max-w-4xl mx-auto px-6 text-center">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
            <TrendingUp size={40} className="text-medical-cyan mx-auto mb-6" />
            <h2 className="text-4xl font-black text-white mb-4">Ready to Transform Your Clinic?</h2>
            <p className="text-blue-200 text-lg mb-8">Join 240+ healthcare providers already using MediSync AI</p>
            <Link to="/login" className="inline-flex items-center gap-2 px-8 py-4 bg-white rounded-xl font-bold text-medical-navy hover:bg-blue-50 transition-all duration-200 shadow-xl hover:-translate-y-1">
              Start Free Trial Today <ArrowRight size={18} />
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-400 py-12">
        <div className="max-w-7xl mx-auto px-6">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-400 flex items-center justify-center">
                <Stethoscope size={16} className="text-white" />
              </div>
              <span className="text-white font-bold">MediSync AI</span>
            </div>
            <p className="text-sm">© 2026 MediSync AI. All rights reserved. Built for the future of healthcare.</p>
            <div className="flex gap-6 text-sm">
              <a href="#" className="hover:text-white transition-colors">Privacy</a>
              <a href="#" className="hover:text-white transition-colors">Terms</a>
              <a href="#" className="hover:text-white transition-colors">Contact</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
